from webapp.automation.assist import (
    ASSIST_SELECT_JOB_KIND,
    create_assist_handler,
    register_assist_job,
)
from webapp.automation.battle import (
    BATTLE_DRY_RUN_JOB_KIND,
    BATTLE_EXECUTE_PLAN_JOB_KIND,
    BATTLE_EXECUTE_SKILLS_JOB_KIND,
    create_battle_execute_plan_handler,
    register_battle_jobs,
)
from webapp.automation.chocolate import (
    CHOCOLATE_INSPECT_JOB_KIND,
    CHOCOLATE_RUN_JOB_KIND,
    create_chocolate_inspect_handler,
    create_chocolate_run_handler,
    register_chocolate_inspect_job,
    register_chocolate_run_job,
)
from webapp.automation.diagnostic import register_diagnostic_job
from webapp.automation.digdig import (
    DIGDIG_EXECUTE_JOB_KIND,
    DIGDIG_INSPECT_JOB_KIND,
    create_digdig_execute_handler,
    create_digdig_inspect_handler,
    register_digdig_execute_job,
    register_digdig_inspect_job,
)
from webapp.automation.completion import (
    BATTLE_COMPLETE_JOB_KIND,
    create_completion_handler,
    register_completion_job,
)
from webapp.automation.entry import (
    BATTLE_PREPARE_JOB_KIND,
    create_battle_entry_handler,
    register_battle_entry_job,
)
from webapp.automation.expball import (
    EXPBALL_INSPECT_JOB_KIND,
    EXPBALL_STORAGE_JOB_KIND,
    EXPBALL_SUMMON_JOB_KIND,
    create_expball_inspect_handler,
    create_expball_storage_handler,
    create_expball_summon_handler,
    register_expball_inspect_job,
    register_expball_storage_job,
    register_expball_summon_job,
)
from webapp.automation.expball_sell import (
    EXPBALL_SELL_JOB_KIND,
    create_expball_sell_handler,
    register_expball_sell_job,
)
from webapp.automation.expball_navigation import (
    EXPBALL_NAVIGATE_JOB_KIND,
    create_expball_navigate_handler,
    register_expball_navigate_job,
)
from webapp.automation.expball_run import (
    EXPBALL_RUN_JOB_KIND,
    create_expball_run_handler,
    register_expball_run_job,
)
from webapp.automation.lottery import (
    LOTTERY_DRAW_JOB_KIND,
    LOTTERY_GIFTBOX_RECEIVE_JOB_KIND,
    LOTTERY_INSPECT_JOB_KIND,
    LOTTERY_NAVIGATE_JOB_KIND,
    LOTTERY_RUN_JOB_KIND,
    create_lottery_draw_handler,
    create_lottery_giftbox_receive_handler,
    create_lottery_inspect_handler,
    create_lottery_navigate_handler,
    create_lottery_run_handler,
    register_lottery_draw_job,
    register_lottery_giftbox_receive_job,
    register_lottery_inspect_job,
    register_lottery_navigate_job,
    register_lottery_run_job,
)
from webapp.automation.program import compile_battle_program
from webapp.automation.quest import (
    FREE_QUEST_ENTER_JOB_KIND,
    MAIN_STORY_ENTER_JOB_KIND,
    create_free_quest_entry_handler,
    create_main_story_entry_handler,
    register_free_quest_entry_job,
    register_main_story_entry_job,
)
from webapp.automation.recovery import (
    BATTLE_RESTART_GAME_JOB_KIND,
    create_recovery_handler,
    register_recovery_job,
)
from webapp.automation.run import (
    FULL_RUN_JOB_KIND,
    create_full_run_handler,
    register_full_run_job,
)
from webapp.automation.stage import (
    BATTLE_DETECT_STAGE_JOB_KIND,
    create_stage_handler,
    register_stage_job,
)

__all__ = [
    "ASSIST_SELECT_JOB_KIND",
    "BATTLE_COMPLETE_JOB_KIND",
    "BATTLE_DETECT_STAGE_JOB_KIND",
    "BATTLE_DRY_RUN_JOB_KIND",
    "BATTLE_EXECUTE_PLAN_JOB_KIND",
    "BATTLE_EXECUTE_SKILLS_JOB_KIND",
    "BATTLE_PREPARE_JOB_KIND",
    "BATTLE_RESTART_GAME_JOB_KIND",
    "CHOCOLATE_INSPECT_JOB_KIND",
    "CHOCOLATE_RUN_JOB_KIND",
    "DIGDIG_INSPECT_JOB_KIND",
    "DIGDIG_EXECUTE_JOB_KIND",
    "EXPBALL_INSPECT_JOB_KIND",
    "EXPBALL_NAVIGATE_JOB_KIND",
    "EXPBALL_RUN_JOB_KIND",
    "EXPBALL_SELL_JOB_KIND",
    "EXPBALL_STORAGE_JOB_KIND",
    "EXPBALL_SUMMON_JOB_KIND",
    "FULL_RUN_JOB_KIND",
    "FREE_QUEST_ENTER_JOB_KIND",
    "MAIN_STORY_ENTER_JOB_KIND",
    "LOTTERY_DRAW_JOB_KIND",
    "LOTTERY_GIFTBOX_RECEIVE_JOB_KIND",
    "LOTTERY_INSPECT_JOB_KIND",
    "LOTTERY_NAVIGATE_JOB_KIND",
    "LOTTERY_RUN_JOB_KIND",
    "compile_battle_program",
    "create_assist_handler",
    "create_battle_entry_handler",
    "create_battle_execute_plan_handler",
    "create_chocolate_inspect_handler",
    "create_chocolate_run_handler",
    "create_digdig_inspect_handler",
    "create_digdig_execute_handler",
    "create_expball_inspect_handler",
    "create_expball_navigate_handler",
    "create_expball_run_handler",
    "create_expball_sell_handler",
    "create_expball_storage_handler",
    "create_expball_summon_handler",
    "create_completion_handler",
    "create_full_run_handler",
    "create_free_quest_entry_handler",
    "create_main_story_entry_handler",
    "create_lottery_draw_handler",
    "create_lottery_giftbox_receive_handler",
    "create_lottery_inspect_handler",
    "create_lottery_navigate_handler",
    "create_lottery_run_handler",
    "create_recovery_handler",
    "create_stage_handler",
    "register_assist_job",
    "register_battle_jobs",
    "register_chocolate_inspect_job",
    "register_chocolate_run_job",
    "register_completion_job",
    "register_battle_entry_job",
    "register_diagnostic_job",
    "register_digdig_inspect_job",
    "register_digdig_execute_job",
    "register_expball_inspect_job",
    "register_expball_navigate_job",
    "register_expball_run_job",
    "register_expball_sell_job",
    "register_expball_storage_job",
    "register_expball_summon_job",
    "register_full_run_job",
    "register_free_quest_entry_job",
    "register_main_story_entry_job",
    "register_lottery_draw_job",
    "register_lottery_giftbox_receive_job",
    "register_lottery_inspect_job",
    "register_lottery_navigate_job",
    "register_lottery_run_job",
    "register_recovery_job",
    "register_stage_job",
]
